Vagrant.configure("2") do |config|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    # Master Nodes
    MasterCount = 1
    (1..MasterCount).each do |i|
      config.vm.define "master-0#{i}" do |master|
        master.vm.box = "oraclelinux/9"
        master.vm.box_check_update = false
        master.vm.hostname = "master-#{i}"
        master.vm.network "private_network", ip: "192.168.56.3#{i}"
  
        master.vm.provider "virtualbox" do |vb|
          vb.name = "master-0#{i}"
          vb.memory = 1048
          vb.cpus = 1
        end
        master.vm.provision "shell", path: "install-kube.sh", privileged: true
      end
    end
  
    # # Worker Nodes
    # WorkerCount = 2
    # (1..WorkerCount).each do |i|
    #   config.vm.define "worker-0#{i}" do |worker|
    #     worker.vm.box = "oraclelinux/9"
    #     worker.vm.box_check_update = false
    #     worker.vm.hostname = "worker-0#{i}"
    #     worker.vm.network "private_network", ip: "192.168.56.5#{i}"
  
    #     worker.vm.provider "virtualbox" do |vb|
    #       vb.name = "worker-0#{i}"
    #       vb.memory = 2048
    #       vb.cpus = 2
    #     end
    #     worker.vm.provision "shell", path: "install-kube.sh", privileged: true
    #   end
    # end
  
    # Provisioning: Áp dụng cho tất cả các máy
    config.vm.provision "shell", inline: <<-SHELL
      if ! id "centos" >/dev/null 2>&1; then
        useradd -m -s /bin/bash centos
        echo "User centos created"
      fi
      mkdir -p /home/centos/.ssh
      echo "#{ssh_pub_key}" >> /home/centos/.ssh/authorized_keys
      chmod 700 /home/centos/.ssh
      chmod 600 /home/centos/.ssh/authorized_keys
      chown -R centos:centos /home/centos/.ssh
      echo "#{ssh_pub_key}" >> /root/.ssh/authorized_keys
      echo "SSH public key added!"
    SHELL
  end