---
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "abcdef.0123456789abcdef"
    apiServerEndpoint: "192.168.122.20:6443" # Địa chỉ IP loadBalancer hoặc IP của server control plane
    caCertHashes:
      - "sha256:b444f6f8a471e80c2c451d6d164cfe1520ab09eaa6e3375e0a238b3bf3ecf1e2"     # --discovery-token-ca-cert-hash
controlPlane:
  certificateKey: "3341432cbb4435e41638999c66362a101b71a0ad9e65e5949c4952bb99bb800c"  #--control-plane --certificate-key
  localAPIEndpoint:
    advertiseAddress: "192.168.122.31" # Địa chỉ IP của server control plane
    bindPort: 6443
nodeRegistration:
  name: "master-02"                   # Tên của node
  criSocket: "unix:///var/run/containerd/containerd.sock"
  ignorePreflightErrors:
    - IsPrivilegedUser
  imagePullPolicy: "IfNotPresent"

# sudo kubeadm join --config join-master-02.yaml