apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
bootstrapTokens:
  - token: "abcdef.0123456789abcdef"
    description: "kubeadm bootstrap token"
    ttl: "24h"
    usages:
      - authentication
      - signing
    groups:
      - system:bootstrappers:kubeadm:default-node-token

nodeRegistration:
  name: "master-01"
  criSocket: "unix:///var/run/containerd/containerd.sock"
  imagePullPolicy: "IfNotPresent"
  imagePullSerial: true
  # Lab only: cho phép workload chạy trên control-plane
  # Production/HA nên bỏ dòng này để kubeadm tự taint control-plane
  # taints: []

localAPIEndpoint:
  advertiseAddress: "192.168.122.30" # Địa chỉ IP của server control plane
  bindPort: 6443

certificateKey: "3341432cbb4435e41638999c66362a101b71a0ad9e65e5949c4952bb99bb800c" # sudo kubeadm certs certificate-key

timeouts:
  controlPlaneComponentHealthCheck: "60s"

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: "v1.36.0"
controlPlaneEndpoint: "192.168.122.20:6443"  # LoadBalancer/Public IP OR Private IP
clusterName: "example-cluster"
certificatesDir: "/etc/kubernetes/pki"       # Directory for TLS certificates
imageRepository: "registry.k8s.io"
encryptionAlgorithm: "ECDSA-P256"

networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/16"
  dnsDomain: "cluster.local"

etcd:
  external:
    endpoints:
      - "https://192.168.122.21:2379"
      - "https://192.168.122.22:2379"
      - "https://192.168.122.23:2379"
    caFile: "/etc/etcd/pki/ca.pem"
    certFile: "/etc/etcd/pki/etcd.pem"
    keyFile: "/etc/etcd/pki/etcd-key.pem"

apiServer:
  certSANs:
    - "192.168.122.20"
    - "192.168.122.30"
    - "192.168.122.31"
    - "master-01"
    - "master-02"

controllerManager: {}
scheduler: {}

dns:
  disabled: false

proxy:
  disabled: true

# sudo kubeadm init --config kubeadm-config.yaml --upload-certs