apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  labels:
    app: argocd
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: argocd-server